name: Build and Push to Artifact Registry & Deploy to Cloud Run

on:
  push:

env:
  PROJECT_ID: wtm-demo
  REGION: asia-southeast2
  GAR_LOCATION: asia-southeast2-docker.pkg.dev/wtm-demo-416609/cr-artifacts
  CLOUD_RUN_SERVICE: wtm-demo

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY_GCP }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t ${{ env.PROJECT_ID }} .

      - name: Tag image
        run: docker tag ${{ env.PROJECT_ID }} ${{ env.GAR_LOCATION }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}

  deploy-to-cloud-run:
    needs: build-push-artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY_GCP }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: 'Deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.CLOUD_RUN_SERVICE }}'
          image: '${{ env.GAR_LOCATION }}'
          region: '${{ env.REGION }}'